package co.com.ceiba.edu.drools.fusion;

import co.com.ceiba.edu.drools.fusion.FlightStatus
import co.com.ceiba.edu.drools.fusion.FlightControl

global co.com.ceiba.edu.drools.fusion.FlightControl control;

declare FlightStatus
    @role(event)
    @timestamp(timestamp)
end

rule "Contacto"
salience 100
when
    $currentFlight : FlightStatus()
    not (exists (FlightStatus(this != $currentFlight, flight == $currentFlight.flight)))
then
    control.addFlight($currentFlight);
    System.out.println("Contacto con el vuelo " + $currentFlight.getFlight());
end
